# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpringBootCli < Formula
  desc "A CLI utility to generate SpringBoot application"
  homepage "https://github.com/sivaprasadreddy/spring-boot-cli"
  version "0.0.5"

  on_macos do
    url "https://github.com/sivaprasadreddy/spring-boot-cli/releases/download/v0.0.5/spring-boot-cli_darwin_amd64.zip"
    sha256 "e3a7dc14167794e374c33d62e572c2526c19f77ecd863f657fe33d1936ae7a34"

    def install
      bin.install "spring-boot-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the SpringBootCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sivaprasadreddy/spring-boot-cli/releases/download/v0.0.5/spring-boot-cli_linux_amd64.zip"
      sha256 "cd4cf9e87fe0eff90df4dc6c45db6ffebc43351892f9a21da01eb304c62069b2"

      def install
        bin.install "spring-boot-cli"
      end
    end
  end

  test do
    system "#{bin}/spring-boot-cli --version"
  end
end
